### ISSUE TITLE
change socketio config dynamically

### ISSUE THREAD

**Issue by gsudhanshu** [rodgc/ngx-socket-io#101]
I am using ngx-socket-io for realtime notifications in angular app

My current requirement is to enable notifications or socketio requests to server only if enabled in settings DB

I was thinking to make this change by changing the socketio module config during runtime, i.e when I get the settings from api call.

my current code in app.module

```
if(environment.angularEnv == "local") {
  config = { url: 'http://localhost:8001', options: {} };
} else {
  config = { url: location.origin, options: {} };
}
```
```
imports: [
    BrowserModule,
    SocketIoModule.forRoot(config),
```

**Comment by Helveg** [comment]
There's many [examples](https://stackoverflow.com/a/60686697/1016004) online how to construct `Socket`s at runtime.

```
var socket = new Socket(config);
```

**Comment by gsudhanshu** [comment]
Can I pass a parameter specifying the interval in which socket-io requests should be sent to server

**Comment by Helveg** [comment]
IIRC the config options are all documented, have a look at them.
