### ISSUE TITLE
Getting 404 error with @nestjs/websockets

### ISSUE THREAD

**Issue by thekhegay** [rodgc/ngx-socket-io#103]
## Server :

```ts
import {
    ConnectedSocket,
    MessageBody,
    OnGatewayConnection, OnGatewayDisconnect, OnGatewayInit,
    SubscribeMessage,
    WebSocketGateway,
    WebSocketServer
} from '@nestjs/websockets';
import { Server, Socket } from 'socket.io';
import { Logger } from '@nestjs/common';

@WebSocketGateway()
export class ChatGateway implements OnGatewayInit, OnGatewayConnection, OnGatewayDisconnect {
    @WebSocketServer()
    server: Server;

    private logger: Logger = new Logger('AppGateway');

    @SubscribeMessage('msgToServer')
    handleMessage(client: Socket, payload: string): void {
        this.server.emit('msgToClient', payload);
    }

    afterInit(server: Server) {
        this.logger.log('Init');
    }

    handleDisconnect(client: Socket) {
        this.logger.log(`Client disconnected: ${client.id}`);
    }

    handleConnection(client: Socket, ...args: any[]) {
        this.logger.log(`Client connected: ${client.id}`);
    }
}
```

## Client side:
```ts
import { SocketIoModule, SocketIoConfig } from 'ngx-socket-io';
const socketConfig: SocketIoConfig = {
    url: 'http://localhost:3000',
    options: {
        path: '/'
    }
};
```

## Error

```
GET http://localhost:3000/?EIO=4&transport=polling&t=NhD2AKw 404 (Not Found)
```

**Comment by Ruslancic** [comment]
+1

**Comment by memee** [comment]
Guys, make sure you're hitting your nestjs server. If you use angular your api might be under `/api`. For me it was like:
```
const config: SocketIoConfig = {
  url: "http://localhost:4200/api",
  options: {},
};
```

**Comment by Ankitrao** [comment]
Hello , i'm having this same error , GET http://localhost:3000/?EIO=4&transport=polling&t=NhD2AKw 404 (Not Found)

I'm trying to open a socket connection from client in angular to server in nest js , i have also, set some proxy in angular app in proxy json

Normal Rest api calls are working through this proxy , only websocket calls are giving 404 not found error

Have anybody solved this yet ?

**Comment by Ruslancic** [comment]
> Hello , i'm having this same error , GET http://localhost:3000/?EIO=4&transport=polling&t=NhD2AKw 404 (Not Found)
> 
> I'm trying to open a socket connection from client in angular to server in nest js , i have also, set some proxy in angular app in proxy json
> 
> Normal Rest api calls are working through this proxy , only websocket calls are giving 404 not found error
> 
> Have anybody solved this yet ? @thekhegay

Have you try to update deps to the latest version? Angular and NetsJS?

**Comment by loicbtd** [comment]
I am experiencing the same 404 error with :
- "@nestjs/platform-socket.io": "^9.1.4",
- "@nestjs/websockets": "^9.1.4",

And "socket.io-client": "^4.5.0" installed in an Angular 14 app.

**Comment by msrumon** [comment]
I'm getting `404` error not while developing, but on production. My *Angular* app is on `15.0.2`, *Nest* on `9.2.1` and this library on `4.4.0` (as of today). I'm using Docker (on Windows 10) for development and the app is running as a Docker container on DigitalOcean's *App Platform*.

**Comment by csulit** [comment]
Same error mine works in dev but not in production.

**Comment by Naikno** [comment]
It works for me using :

**client**
Angular 15,    "ngx-socket-io": "^4.4.0",
with this config : 
`const config: SocketIoConfig = { url: 'ws://localhost:3004', options: { transports: ['websocket'] } };
`
**server**
Nestjs  9,   @nestjs/platform-socket.io": "^9.2.1",    "@nestjs/websockets": "^9.2.1",
with this config : 
`@WebSocketGateway(3004, { transports: ['websocket']})`

**Comment by carmonac** [comment]
Using a different port it works but using the same port it happens the bug.

**Comment by VoNo1412** [comment]
My nestjs using the same port but it didn't work 404

**Comment by Ruslancic** [comment]
> > After a couple of years, I'm finally found a solution in my infrastructure. I use nginx as reverse proxy, so `Update` and `Connection` headers must be added:
> > proxy_set_header Upgrade $http_upgrade;
> > proxy_set_header Connection "upgrade";
> 
> I just test in my local server and I using postman not related nginx pro I've had websocket and server is the same port

which version of @nestjs/websockets and @nestjs/websockets @nestjs/platform-socket.io do you use?
