### ISSUE TITLE
fromEvent not getting any message

### ISSUE THREAD

**Issue by jackli199311** [rodgc/ngx-socket-io#107]
I'm trying to get event message from socket.io in Angular. I can see the messages in Chrome dev tools so I think my server is working fine. My Angular code for getting the messages is not working. I subscribed to OnFetchOrders() in my component and I want to print the data to console. But Nothing within my subscription is run.
My service:

    import { Injectable } from '@angular/core';
    import { Socket } from 'ngx-socket-io'; 
    import { map } from 'rxjs/operators';
    
    @Injectable({
	    providedIn: 'root'
    })
    export class SocketService {
	    constructor(private socket: Socket) {
	    }
    
	    // listen event
	    OnFetchOrders() {
		    return this.socket.fromEvent('order_event').pipe(map((data: any) => {
			    console.log('ssssss')
			    return data.msg;
		    }));
	    }
    }

My component:

    import { Component, OnInit } from '@angular/core';
    import { SocketService } from 'src/app/services/socket.service';
    
    @Component({
	    selector: 'app-list',
	    templateUrl: './list.component.html',
	    styleUrls: ['./list.component.css']
    })
    export class ListComponent implements OnInit {
	    
    
	    constructor(
		    private socketService: SocketService,
	    ) { }
    
	    ngOnInit(): void {
		    this.socketService.OnFetchOrders().subscribe((data: any) => console.log(data))
	    }
    
    }

My module:

    import { NgModule } from '@angular/core';
    import { BrowserModule } from '@angular/platform-browser';
    import { FormsModule, ReactiveFormsModule } from '@angular/forms';
    
    import { AppComponent } from './app.component';
    import { HeaderComponent } from './components/comman/header/header.component';
    import { ListComponent } from './components/pages/movies/list/list.component';
    import { FormComponent } from './components/pages/movies/form/form.component';
    
    import { SocketIoModule, SocketIoConfig } from 'ngx-socket-io';
    import { ModalModule } from 'ngx-bootstrap/modal';   
    
    const config: SocketIoConfig = {
	    url: 'http://localhost:4000/',
	    options: {
		    transports: ['websocket']
	    }
    }
    
    @NgModule({
	    declarations: [
		    AppComponent,
		    HeaderComponent,
		    ListComponent,
		    FormComponent
	    ],
	    imports: [
		    BrowserModule,
		    SocketIoModule.forRoot(config),
		    ModalModule.forRoot(),  
		    FormsModule,
		    ReactiveFormsModule 
	    ],
	    providers: [],
	    bootstrap: [AppComponent]
    })
    export class AppModule { }

**Comment by Alan4747** [comment]
Has this issue been resolved?

**Comment by Alan4747** [comment]
I solved this problem temporarily like this:

In your **SocketService**

`data: any = [];`
`
 OnFetchOrders() {
	    return  this.data = this.socket.ioSocket.receiveBuffer;
    }
`

**Comment by shyambandla** [comment]
From::

 return this.socket.fromEvent('order_event').pipe(map((data: any) => {
		    console.log('ssssss')
		    return data.msg;
	    }));

change data

to::

 return this.socket.fromEvent('order_event').pipe(map((data: any) => {
		    console.log('ssssss')
		    return data;
	    }));
use this

**Comment by JoelAH** [comment]
@jackli199311 have you solved. Having the same issue

**Comment by vdiaz1130** [comment]
I'm having this problem. It's only with the `fromEvent` as the `this.socket.emit` works as expected. Any ideas what I may be doing wrong?

```
  // Packages
  "@nestjs/platform-socket.io": "^9.0.11",
  "@nestjs/websockets": "^9.0.11",
  "ngx-socket-io": "^4.3.0",
  "socket.io": "^4.5.2",
  "socket.io-client": "^4.5.2",
```

```
  // Module
  import { SocketIoModule, SocketIoConfig } from 'ngx-socket-io';
  const url = `${environment.api.root}:${environment.api.port}`;
  const config: SocketIoConfig = { url: url, options: {} };

  @NgModule({
  imports: [
    ...,
    SocketIoModule.forRoot(config),

  ]
  ...
  })
  export class AppModule {}
```
```
  ...
  // Component
  import { Socket } from 'ngx-socket-io';
  ...
  private sendInvalidateCacheMessage(clientId: string, collectionName: keyof ClientData) {
    this.socket.emit('invalidateCache', {collectionName, clientId});
  }

  private getInvalidateCacheMessage() {
    return this.socket.fromEvent(`invalidateCache`)
      .pipe(map((data: any) => {
        console.log(data); // <- This is NOT executed
        return data;
      }));
  }
```
```
  // Server
  import { OnModuleInit } from '@nestjs/common';
  import { MessageBody, SubscribeMessage, WebSocketGateway, WebSocketServer } from '@nestjs/websockets';
  import { Server } from 'socket.io';

  @WebSocketGateway({
    cors: {
      origin: "http://localhost:4200"
    }
  })
  export class Gateway implements OnModuleInit {
    @WebSocketServer()
    private server: Server;
    
    onModuleInit() {
      this.server.on('connection', (socket) => {
        console.log(socket.id);
        console.log('connected');
      });
    }

    @SubscribeMessage('invalidateCache')
    onNewMessage(@MessageBody() body: any) {
      console.log(body); // <- This is executed
      this.server.emit(`invalidateCache`, {
        msg: `invalidateCache`,
        ...body
      })
    }
  }
```

**Comment by vdiaz1130** [comment]
Never mind. I had to subscribe. Duh!

**Comment by Antonyodu** [comment]
@vdiaz1130 You could have shared the exact code used
