### ISSUE TITLE
auth field on options

### ISSUE THREAD

**Issue by xam8re** [rodgc/ngx-socket-io#110]
Seems missing auth field on option used on doc:
https://socket.io/docs/v4/client-initialization/#auth

**Comment by ldeluigi** [comment]
This is breaking things for me....

**Comment by hoberlaender** [comment]
That is a problem, xam8re described in a right way. With version 4.0.0 the SocketIoConfig interface implemented options as any. With version 4.1.0 the interface is set but auth option is missing.

**Comment by geo242** [comment]
@xam8re @Helveg This is still a problem. Any word on a resolution?

**Comment by Helveg** [comment]
@geo242 There are some PR's adding extra typing information, like [this](https://github.com/rodgc/ngx-socket-io/pull/115/files), do you think you could PR this?

**Comment by Kaylleur** [comment]
Why just not use the original socket.io package typing `Partial<ManagerOptions & SocketOptions>`.

**Comment by geo242** [comment]
@Helveg here you go... https://github.com/rodgc/ngx-socket-io/pull/140

**Comment by Helveg** [comment]
thanks!
