### ISSUE TITLE
Options missing "extraHeaders"

### ISSUE THREAD

**Issue by Witzler** [rodgc/ngx-socket-io#112]
The interface of **SocketIoConfig** options is missing the "_extraHeaders_" attribute.
I tested it myself and it worked flawlessly. Since the socket.io-client supports it for a while now, it should definetly be a thing.
[Docs](https://socket.io/docs/v4/client-options/#extraheaders)

```typescript
export interface SocketIoConfig {
   ...
   options?: {
      ...
      extraHeaders?: {
         [header: string]: string;
      };
   }
}
```

**Comment by Ruslancic** [comment]
+1

**Comment by felixphase** [comment]
How can I get this "extraHeaders" in my current installed project?

**Comment by Helveg** [comment]
npm install the current master branch
