### ISSUE TITLE
Bump version to Angular v13.x.x

### ISSUE THREAD

**Issue by Mondei1** [rodgc/ngx-socket-io#118]
Version 13.x.x of Angular is released but `ngx-socket-io` still depends on 12.x.x.x which is why I cannot use it in my project right now. A `--force` does the job without breaking anything but it always give me a high pulse everytime I use it :fearful: 
```
> $ npm i ngx-socket-io           
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: xxx@0.0.0
npm ERR! Found: @angular/common@13.0.2
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"~13.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^12.0.0" from ngx-socket-io@4.1.0
npm ERR! node_modules/ngx-socket-io
npm ERR!   ngx-socket-io@"*" from the root project
```

Would be awesome if you could bump that dependency if it does not break everything.

**Comment by nclsstdl** [comment]
same here, any news on this issue?

**Comment by helgetan** [comment]
any updates here?

**Comment by kylecordes** [comment]
The new Node dependency behavior is leading to a *lot* of similar excitement around the JS ecosystem.

**Comment by cgraamans** [comment]
Any news on this issue, devs? I hope you guys can look into this asap, as the new Angular version has been out for more than a month now.

**Comment by HyperLife1119** [comment]
I have a better library: https://www.npmjs.com/package/ngx-socketio2
It supports angular 13!

**Comment by Mondei1** [comment]
@cgraamans Like I said, you can use `npm i --force` without breaking anything. Atleast it didn't broke anything in my project. It should install and be usable out-of-the-box.

**Comment by Sampath-Lokuge** [comment]
Hi, Any update about Angular 13+ support. Thanks!

**Comment by heuristicAL** [comment]
There doesn't seem to be much activity on the repo, unfortunately...
Hopefully we don't need to fork it and start offering an alternative.

**Comment by raphael22** [comment]
@Mondei1 
--force is a bit overkill here
you can simple go for legacy-peer-deps in your .npmrc

**Comment by Mondei1** [comment]
> @Mondei1 --force is a bit overkill here you can simple go for legacy-peer-deps in your .npmrc

Oh, didn't knew that. Thanks. Well, if it works, it works I guess 😅

**Comment by nelson777** [comment]
@HyperLife1119  is this library compatible with ngx-socket-io or we have to rewrite the code ?

**Comment by HyperLife1119** [comment]
> @HyperLife1119 is ngx-socketio2 compatible with ngx-socket-io or we have to rewrite the code ?

This `ngx-socketio2` library it rewrites the code. If you read the `README.md`, you will find that the API differences between them are similar, and the migration cost is small.
