### ISSUE TITLE
Options missing "extraHeaders"

### ISSUE THREAD

**Issue by Rub0013** [rodgc/ngx-socket-io#119]
For using 'extraHeaders' option user have to install the master branch directly. Installing the latest(4.1.0) version does not solve the problem. I think publish is needed in NPM registry.

**Comment by ArtashMardoyan** [comment]
We also have the same issue.
We need to send the authorization token by header.
But Your latest(4.1.0) version does not support it.

**Comment by raffi-k** [comment]
Same issue here

**Comment by ThomasOliver545** [comment]
Hi,
fyi i implemented the following workaround in my app, till a new version gets released.
If you want you can take a look here:
https://github.com/ThomasOliver545/real-time-chat-nestjs-angular/blob/main/frontend/src/app/private/sockets/custom-socket.ts

**Comment by HyperLife1119** [comment]
I have a better library: https://www.npmjs.com/package/ngx-socketio2
