### ISSUE TITLE
how send extra data on connection??

### ISSUE THREAD

**Issue by santiagoalmeidabolannos** [rodgc/ngx-socket-io#12]
i hope solve a problem like this https://stackoverflow.com/questions/4743592/send-additional-data-on-socket-connection

**Comment by jasminexie** [comment]
I'm assuming that you do this exactly like how you would in socket.io-client.

angular client:
```typescript
import { SocketIoModule, SocketIoConfig } from 'ngx-socket-io';

const config: SocketIoConfig = { url: 'http://localhost:8988', options: {query: "param1=value1&param2=value2"} };

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    SocketIoModule.forRoot(config)
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

express server:
```js
var app = require('express')();
var server = require('http').Server(app);
var io = require('socket.io')(server ,{
    cookie: false, // some custom config here
    pingTimeout: 30000,
    pingInterval: 2000
});

io.sockets.on('connection', function (socket) {
  const query = socket.handshake.query;

  socket.on('event', function() { ... })
}

// query['param1'] = value1
// query['param2'] = value2
```

**Comment by monurakkaya** [comment]
@jasminexie what if params come from localstorage or websql?

**Comment by monurakkaya** [comment]
@jasminexie thanks for the explanation. But i'm using this package with @ionic/storage so i can't get token synchronously.. 

```
let token = this.storage.get('token')
      .then(data => {
        return data
      })
```
also i need to inject this storage module somewhere to reach ionic/storage.. normally i do it on service or provider's constructor. I couldn't figure out how to do that. Should i use localstorage to keep only token? What would advice?

**Comment by Art2058** [comment]
@jasminexie same

**Comment by sandeepsuvit** [comment]
This worked for me

`@Injectable()
export class CustomSocket extends Socket {

    constructor(
        // Has got implementation to get fetch token from localstorage
        private authService: AuthService
    ) {
        super({ url: 'http://url_two:portTwo', options: {} });

        // Set token as part of the query object
        this.ioSocket.query = {
            token: (() => this.authService.getAccessToken() ? this.authService.getAccessToken().token : null)()
        };
    }

}`

**Comment by sandeepsuvit** [comment]
This worked for me
`
@Injectable()
export class CustomSocket extends Socket {

    constructor(
        // Has got implementation to get fetch token from localstorage
        private authService: AuthService
    ) {
        super({ url: 'http://url_two:portTwo', options: {} });

        // Set token as part of the query object
        this.ioSocket.query = {
            token: (() => this.authService.getAccessToken() ? this.authService.getAccessToken().token : null)()
        };
    }

}

`

**Comment by sandeepsuvit** [comment]
This worked for me

```javascript
@Injectable()
export class CustomSocket extends Socket {

    constructor(
        // Has got implementation to get fetch token from localstorage
        private authService: AuthService
    ) {
        super({ url: 'http://url_two:portTwo', options: {} });

        // Set token as part of the query object
        this.ioSocket.query = {
            token: (() => this.authService.getAccessToken() ? this.authService.getAccessToken().token : null)()
        };
    }

}
```

**Comment by Loown** [comment]
Someone found a solution ?? can't send my token that I get from ionic storage

**Comment by turtle0x1** [comment]
Would also like to know!

**Comment by Helveg** [comment]
Something like this should work:

```javascript
import {Socket, SocketIoConfig } from 'ngx-socket-io';

@Injectable({providedIn: 'root'})
export class AsyncSocketService {
  constructor() { }

  public createAsync(Observable<SocketIoConfig> config$) {
    return config$.pipe(map(config => new Socket(config)));
  }
}
```

You could use this as follows:

```javascript
  this.asyncSocketService.createAsync(this.tokenService.getToken()).subscribe(
    socket => {
      console.log("Socket created", socket);
    }
  )
```

The trick is to create the socket only once the asynchronous configuration has been fetched: I don't think that's possible using the dependency injection approach, but you can just use the constructor.

**Comment by ctfrancia** [comment]
It's been 2 years, so just to clean the clutter I'm going to close this issue, If you still have issues please open up a new one
