### ISSUE TITLE
Error Maximum call stack size exceeded

### ISSUE THREAD

**Issue by CrackerakiUA** [rodgc/ngx-socket-io#13]
I got this error after some movements between modules. My socket config is in root module, 
```
import { SocketIoModule, SocketIoConfig } from 'ngx-socket-io';
const config: SocketIoConfig = { url: window.location.origin, options: {} };
@NgModule({
  declarations: [
    ...
  ],
  imports: [
    ...
    SocketIoModule.forRoot(config),
    ...
  ],
  providers: [
    ...
  ],
  bootstrap: [AppComponent]
})
```
and the error log
```
ERROR RangeError: Maximum call stack size exceeded
    at Function.[Symbol.hasInstance] (<anonymous>)
    at hasBinary (index.js:46)
    at hasBinary (index.js:58)
    at hasBinary (index.js:58)
    at hasBinary (index.js:37)
    at hasBinary (index.js:58)
    at hasBinary (index.js:58)
    at hasBinary (index.js:37)
    at hasBinary (index.js:58)
    at hasBinary (index.js:58)
```
which tell generally that we call function inside function. That's error popup when I do simple emit
```
this.socket.emit("to", obj);
```

**Comment by rodgc** [comment]
I'm assuming you're subscribing to the socket, Try adding distinctUntilChanged() in the pipeline just before subscribe().

How often do you send data to the socket?
Do you close or destroy the connection when you change modules?
Do you create new connections every time you hit a page that need a socket?

**Comment by CrackerakiUA** [comment]
ok, this issue is relative to socket.io-client, so I am closing this topic.
