### ISSUE TITLE
Distribution with Ivy distribution version 4.2.0

### ISSUE THREAD

**Issue by rickynguyen4590** [rodgc/ngx-socket-io#131]
I see version 4.2.0 updated to `@angular/core@13`  already. But the installed version on my project still using *Legacy View Engine* distribution . I've tried to build *ngx-socket-io" in local then output is good and Ivy compatible. Below pic, on the left shows `ngx-socket-io` under `node_modules` on the right show the result after run `npm build`

![image](https://user-images.githubusercontent.com/2346112/170628192-467d82e0-d33b-450a-ae96-4463a247765e.png)

Even though 4.2.0 depends on Ng 13 already but I still see the compatible warning message..
```
>  NX  Angular CLI has been decorated to enable computation caching.

Processing legacy "View Engine" libraries:
- ngx-socket-io [es2015/esm2015] (git+ssh://git@github.com/rodgc/ngx-socket-io.git)
- ngx-socket-io [main/umd] (git+ssh://git@github.com/rodgc/ngx-socket-io.git)
Encourage the library authors to publish an Ivy distribution.
```

**Comment by rickynguyen4590** [comment]
Close this issue because lib supports angular 14.

**Comment by Helveg** [comment]
Could you detail what needs to be done to fix this, or submit a PR?
