### ISSUE TITLE
Support Angular 14

### ISSUE THREAD

**Issue by Karman40** [rodgc/ngx-socket-io#133]
I tested angular under 14 and everything works, so I think it would be enough to just update the peer dependencies.

**Comment by RRGT19** [comment]
During the upgrade to Angular v14:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! Found: @angular/common@14.0.2
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"^14.0.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^13.0.0" from ngx-socket-io@4.2.0
npm ERR! node_modules/ngx-socket-io
npm ERR!   ngx-socket-io@"^4.2.0" from the root project
```

Please update peer dependencies.

**Comment by fhemery** [comment]
Hey there,

Being in need of the package for version 14, I made a PR. Waiting for the boss to review and publish the new package if everything is ok 😋
