### ISSUE TITLE
BeforeUnload Optionality

### ISSUE THREAD

**Issue by onebrother21** [rodgc/ngx-socket-io#139]
I would like to have access to the "closeOnBeforeunload" option of the underlying socket.io options. Doing so allows me to fire closing events specific to one set of business logic vs another, instead of cleaning up (and thus exposing) different business concerns in the "disconnect" event solely. Thanks for a great package btw!

**Comment by onebrother21** [comment]
Any acknowledgement or ETA?

**Comment by Helveg** [comment]
I'm not sure I understand what you're requesting? Could you demonstrate what you'd like with a code snippet?

**Comment by Helveg** [comment]
@onebrother21 feel free to reopen if you're still interested in following up on this issue!
