### ISSUE TITLE
dependecy socket.io-parser 4.2.4 audit fix breaks ngx-socket-io

### ISSUE THREAD

**Issue by kasiim** [rodgc/ngx-socket-io#158]
dependecy socket.io-parser audit fix breaks ngx-socket-io

https://github.com/advisories/GHSA-cqmj-92xf-r6r9

vers 4.2.4 keeps creating socket connections until all ports are taken resulting in denial of service.

**Comment by limcheyyong** [comment]
I had the same issue. I resolved this problem by fixing the version of 'socket.io-parser' in 'pnpm-lock.yaml' to 4.2.3. But This method may not be the most effective way to resolve the issue,
