### ISSUE TITLE
Make connection conditionally 

### ISSUE THREAD

**Issue by yan-loong** [rodgc/ngx-socket-io#166]
My issue revolves around the need **to establish a socket connection based on the result of an asynchronous task, such as an XMLHttpRequest.** The challenge I'm facing is that, according to this package, developers are required to import the SocketIoModule with its configuration synchronously in the app module.

I attempted to use a useFactory function to conditionally provide a custom socket service. However, my efforts were unsuccessful because the useFactory function cannot return a promise, thus lacking support for asynchrony.

I am hesitant to use the APP_INITIALIZER token since I don't want my entire app to be dependent on this asynchronous task.

Could you please review and provide guidance on this issue?"

**Comment by Helveg** [comment]
The `SocketIoModule` is just a thin wrapper around the `Socket` constructor. Instead of rigging the module, and having it provide the `Socket` class to the dependency injection system, you can also just call the `Socket` constructor whenever you want:

```
import { Socket } from 'ngx-socket-io';

const socket = new Socket(config);
```

**Comment by yan-loong** [comment]
Thanks for your advice, it works like a charm.

**Comment by Helveg** [comment]
Glad to be of assistance :)
