### ISSUE TITLE
ngx-socket-io@4.6.0 install error in angular@17.3.0

### ISSUE THREAD

**Issue by surjendu104** [rodgc/ngx-socket-io#176]
I have ran this command : `npm i ngx-socket-io@4.6.0` to install it in `angular@17.3.0`
but getting thsi error
![ngx-socket-io-install-error](https://github.com/rodgc/ngx-socket-io/assets/101238933/75e078b7-68fd-4794-9a01-f2965079f717)

**Comment by surjendu104** [comment]
@rodgc ps look into it

**Comment by AngelZaragoza** [comment]
@surjendu104 I had the same exact issue, but it successfully installed using the 4.6.1 version:
![image](https://github.com/user-attachments/assets/16dff49c-998c-4b55-8e65-d17354a6993d)

**Comment by Anonymous777-ind** [comment]
try this command

npm i ngx-socket-io --legacy-peer-deps

**Comment by surjendu104** [comment]
> try this command
> 
> npm i ngx-socket-io --legacy-peer-deps

it worked!! thanks @Anonymous777-ind
