### ISSUE TITLE
Angular 7 Uncaught ReferenceError: global is not defined

### ISSUE THREAD

**Issue by stherrienaspnet** [rodgc/ngx-socket-io#18]
I'm getting this error into an Angular 7 application. Do i need to include the following line
(window as any).global = window;? Thanks for your help :)

**Comment by stherrienaspnet** [comment]
adding this line fixed the issue (window as any).global = window; I thought this line was only required using angular 6.x version.

**Comment by bharat-banavalikar** [comment]
This solution worked for chrome , firefox and edge browsers. Any suggestion for IE11 browser ?

**Comment by AviwT** [comment]
> This solution worked for chrome , firefox and edge browsers. Any suggestion for IE11 browser ?

For me this solution works for any browser, including IE11 (11.1146.16299.0) and Edge (41.16299.1004.0)

**Comment by jcpc91** [comment]
Why is not document this problem an solution
