### ISSUE TITLE
Establish compatibility to Angular 19

### ISSUE THREAD

**Issue by BernhardBehrendt** [rodgc/ngx-socket-io#183]
Actually it's not possible to update to Angular 19 due to peer dependency to Angular 18 in ngx-socket-io.

**Comment by destlaver** [comment]
I'm still unable to install it with ang@19 doing npm i ngx-socket-io or npm i ngx-socket-io@latest

npm ERR! Could not resolve dependency:
npm ERR! peer @angular/core@"^18.0.0" from ngx-socket-io@4.8.0
