### ISSUE TITLE
ERROR TypeError: this.socket.fromEvent(...).map is not a function

### ISSUE THREAD

**Issue by dreamdevil00** [rodgc/ngx-socket-io#2]
Although I  do 
```
import 'rxjs/add/operator/map'
```
 in my chat.service, It always show the error

```
ERROR TypeError: this.socket.fromEvent(...).map is not a function
```
I found that there's no method ```map``` in the Observable at all,  and when I add 
```
import 'rxjs/add/operator/map'
```
 to the source code file socket-io.service.js
 Everything is ok

Is there somthing wrong with my code  or bug in the code ? Please help me. Thanks a lot.

**Comment by rodgc** [comment]
Hi @dreamdevil00 

Your method should be something like this

`chat.service.ts`
```typescript
import { Observable } from 'rxjs/Observable'
import 'rxjs/add/operator/map'; 

getChat() {
  return this.socket
    .fromEvent<any>("chat")
    .map(data => data.chat);
}
```

**Comment by dreamdevil00** [comment]
oh,  I made another clean project and tested again. It's ok. Thanks for your help!
I have to do something to find what  the problem is

**Comment by CrackerakiUA** [comment]
how did you solve this issue? I am calling this this.getChat() from constructor and have the error mentioned.
