### ISSUE TITLE
How to use .of(namespace)?

### ISSUE THREAD

**Issue by joschne** [rodgc/ngx-socket-io#25]
Hi! i was trying to use .of(namespace) but I could not figure out how to use it. 

When I injected Socket in my Angular Service and called .of('myNamespace') on the WrappedSocket instance I got the error:

`
ERROR TypeError: this.ioSocket.of is not a function
    at WrappedSocket.push../node_modules/ngx-socket-io/src/socket-io.service.js.WrappedSocket.of (socket-io.service.js:21)
 `

It would be great to have a little documentation / an example about how to use this function.

Thank you!

**Comment by etherealyn** [comment]
I also couldn't figure out how to use it.

However, if _chat_ is your namespace, then you need to supply it in the _url_ of configuration like this:

`const config: SocketIoConfig = {url: 'http://localhost:8080/chat', options: {}};`

Be aware that this would restrict you to _chat_ namespace globally for each socket. To avoid that, I would suggest using something like this:

```
import { Injectable, NgModule } from '@angular/core';
import { Socket } from 'ngx-socket-io';

@Injectable()
export class ChatSocket extends Socket {
  constructor() {
    super({url: 'http://localhost:8080/chat', options: {}});
  }
}

@NgModule({
  declarations: [
    //components
  ],
  imports: [
    SocketIoModule,
    //...
  ],
  providers: [ChatSocket],
  bootstrap: [/** AppComponent **/]
})
export class AppModule { }
```

**Comment by lincond** [comment]
I have the same error when trying to use .of(). Any updates on this?

**Comment by seba-salavilla** [comment]
In socketservices you can use this.socket.ioSocket.nsp = "/mynamespace"

**Comment by FaisalAbid** [comment]
Any update?

**Comment by atao60** [comment]
"of" is meaningless on the client side. See Socket.io doc: [Restricting yourself to a namespace](https://socket.io/docs/#Restricting-yourself-to-a-namespace). 
The @etherealyn's [answer](https://github.com/rodgc/ngx-socket-io/issues/25#issuecomment-465701897)  above is almost right. Just remplace:
`{ url: 'http://localhost:8080/chat', options: { } }`
with:
`{ url: 'http://localhost:8080', options: { path: /chat'' } };`

**Comment by the-pinky-man** [comment]
I had to use `{ url: 'http://localhost:8080/chat', options: { } }`

**Comment by Kuppusamy-R** [comment]
Hi there,

I've achieved namespace like below ,

```typescript
import { Socket, SocketIoConfig } from 'ngx-socket-io';

export class SocketNameSpace extends Socket{
  constructor(socketConfig: SocketIoConfig){
    super(socketConfig);
  }
}


@Component(........) // metadata goes here
export class MyComponent{
    chat: SocketNameSpace;
    news: SocketNameSpace;

    constructor(private socket: Socket){
        // this.socket is for root
        this.chat  = new SocketNameSpace({url: 'http://localhost:3000/chat',options: {} });
        this.news  = new SocketNameSpace({url: 'http://localhost:3000/news',options: {} });
   }
}

```

It works fine and awesome!!!

**Comment by imovertheinternet** [comment]
@Kuppusamy-R How are you achieving that? I get a `ERROR in Can't resolve all parameter` when trying to `super(socketConfig);`  inside SocketNameSpace

**Comment by imovertheinternet** [comment]
@Kuppusamy-R How are you achieving that? I get a ERROR in Can't resolve all parameter when trying to super(socketConfig); inside SocketNameSpace

**Comment by ctfrancia** [comment]
I am going to close this as  it has been over a year, if you still need to please open up a new ticket

**Comment by johaven** [comment]
I prefer to reimplement **of** like this
```javascript
of(namespace: string) {
        const socketInstance = new Socket({url: `${window.location.origin}/${namespace}`})
        this.ioSocketsNameSpaced.push(socketInstance)
        return socketInstance
    }
```
Because if you don't store all sockets in same service, you have to disconnect independently all of them.
An example to manage all socket instances:
```javascript
disconnect(close?: any) {
        for (const nsp of this.ioSocketsNameSpaced) {
            nsp.disconnect()
        }
        return this.ioSocket.disconnect.apply(this.ioSocket, arguments)
    }
```

**Comment by eddietal2** [comment]
> Hi there,
> 
> I've achieved namespace like below ,
> 
> ```ts
> import { Socket, SocketIoConfig } from 'ngx-socket-io';
> 
> export class SocketNameSpace extends Socket{
>   constructor(socketConfig: SocketIoConfig){
>     super(socketConfig);
>   }
> }
> 
> 
> @Component(........) // metadata goes here
> export class MyComponent{
>     chat: SocketNameSpace;
>     news: SocketNameSpace;
> 
>     constructor(private socket: Socket){
>         // this.socket is for root
>         this.chat  = new SocketNameSpace({url: 'http://localhost:3000/chat',options: {} });
>         this.news  = new SocketNameSpace({url: 'http://localhost:3000/news',options: {} });
>    }
> }
> ```
> 
> It works fine and awesome!!!

This solution worked for me. For anyone reading this, don't forget to import SocketIoModule and SocketIoConfig to your app.module.ts, as well as  SocketIoModule.forRoot(config) in the imports. After that, you can just create the SocketNameSpace class in whatever component is needed (App.component for me).

**Comment by yiqu** [comment]
Above solution works great. It should be in the documentation.

**Comment by Helveg** [comment]
I can look into writing docs for this but I'm not up to date with namespaces in socket.io;

* Could someone concisely explain to me the issue and proposed community solution in this thread?
* Are there any actionable points for changes to the code to facilitate the proposed solution?

**Comment by sucotronic** [comment]
@Helveg I think putting the code example as doc would do the trick.

**Comment by Helveg** [comment]
Ok, so then `.of("namespace")`  should just be done on the client-side by creating a socket that connects to `baseUrl + '/namespace'` if I understand correctly?

**Comment by sucotronic** [comment]
@Helveg yep, it's something that's user configurable throught the socket options, as noted in https://github.com/rodgc/ngx-socket-io/issues/25#issuecomment-609040721 We can just put mention in the README something like "to use namespaces (link to https://socket.io/docs/v4/namespaces/#Client-initialization) just pass the namespace in the path like the following:".
