### ISSUE TITLE
ERROR in node_modules/ngx-socket-io/node_modules/rxjs/internal/types.d.ts(81,44): error TS1005: ';' expected.

### ISSUE THREAD

**Issue by rafaneri** [rodgc/ngx-socket-io#26]
This error is related with the issue https://github.com/ReactiveX/rxjs/issues/4511

### Current Behavior
I am getting following errror after using ng build --prod on Amazon CodeBuild

ERROR in node_modules/ngx-socket-io/node_modules/rxjs/internal/types.d.ts(81,44): error TS1005: ';' expected.
node_modules/ngx-socket-io/node_modules/rxjs/internal/types.d.ts(81,74): error TS1005: ';' expected.
node_modules/ngx-socket-io/node_modules/rxjs/internal/types.d.ts(81,77): error TS1109: Expression expected.

Expected behavior
ng build command should run without any error.

Environment

Runtime: Node.js 8.x LTS Carbon and npm
ngx-socket-io version: 2.1.1
RxJS version: 6.4.0

**Comment by Rest11** [comment]
I had the same error in the local project.
Angular CLI: 1.7.4
Node: 10.15.3
OS: win32 x64
Angular: 5.2.9

I've installed version 1.0.8 and it works correctly. Version 1.1.1 or 1.1.0 didn't work for me

**Comment by ctfrancia** [comment]
hey I am going to to close this as it's over a year, if the issue still remains then please open up a new ticket
