### ISSUE TITLE
unable to get server data in ngx-socket-io

### ISSUE THREAD

**Issue by swathibhe** [rodgc/ngx-socket-io#27]
Hi,
I wood like to request you to please help to solve this problem.
i am using ngx-socket-io repository , angular 6. i am connect to the server but i am unable to get the data from the server.
my code is

app.module.ts
import { SocketIoModule, SocketIoConfig } from 'ngx-socket-io';
const config: SocketIoConfig = { url: 'http://af098cb1.ngrok.io', options: {} };
 imports: [
    SocketIoModule.forRoot(config),
}

socket.services.ts file

 constructor(private socket: Socket) { 
    }
 
getMessage() {
        return this.socket
            .fromEvent<any>("sendchat")
            .map(data =>  data.msg);
            
    }
getData(){
console.log("-----------");
this.socket.on('sendchat', function (socket) {
            console.log('User data', socket);
        });
}

output:
it prints this ----------------------
but can not get the  user data and response.and also i not get the single error message i cont understand whats going on please help out.

**Comment by seba-salavilla** [comment]
You need to subscribe to the event getData

SocketServices.ts
```
import { map } from 'rxjs/operators'
getData() {
    return this.socket.fromEvent("sendchat").pipe(map( data => data )); // with pipe rxjs6
}
```

Then in your component class

Home.ts
```
constructor(private socketServices : SocketServices){
    this.socketServices.getData().subscribe( (data) => {
        console.log('User data', data);
    })
}
```

salute.

**Comment by FeLiX-LiM** [comment]
+1

**Comment by FeLiX-LiM** [comment]
Angular 7.2.0 cant't get data fromEvent and emit data

**Comment by swathibhe** [comment]
Ok thanks, I got the solution

**Comment by 3adeling** [comment]
@swathibhe what was the solution?!

**Comment by Helveg** [comment]
The solution was to subscribe to the Observable returned by `.on(...)`

**Comment by swathibhe** [comment]
Yes, I did the same 1 year ago
