### ISSUE TITLE
Using multiple sockets

### ISSUE THREAD

**Issue by thierce** [rodgc/ngx-socket-io#28]
Trying to use two sockets as per instructions gives me errors.
I have added socket in providers array in page module.
`providers: [Socket]`

In app.module:
import { Socket } from 'ngx-socket-io';
and the two export class SocketOne extends Socket { ...

providers: [
    SocketOne, SocketTwo,

This is in an Ionic 4 /Angular 7 app.

This is my error:
ERROR Error: Uncaught (in promise): Error: StaticInjectorError(AppModule)[WrappedSocket -> InjectionToken __SOCKET_IO_CONFIG__]: 
  StaticInjectorError(Platform: core)[WrappedSocket -> InjectionToken __SOCKET_IO_CONFIG__]: 
    NullInjectorError: No provider for InjectionToken __SOCKET_IO_CONFIG__!

**Comment by ambrzz** [comment]
same here!

**Comment by thierce** [comment]
I went this route:

I have two services, each accessing a socket, or in my case, different Namespaces of the same socket.
In each service, I use the following:

```
@Injectable({providedIn: 'root'})
export class Socket1 extends Socket {
  constructor() {
    super({url: 'https://somefunkydomain:3001/thenamespace', options: {}});
  }
}
```
"thenamespace" is all that is changed between the two services.
In the service constructor:
public socket: Socket1,

Now I just access each socket, from each service as I need them.

**Comment by bvandenbon** [comment]
Or just don't use a provider at all for the `Socket` instance.

e.g. you could use a `connect(url)` method to instantiate the socket.

In my application, the URL is not known in advance, but is returned from a webservice.
So, in that case I use the connect method below.

```
  connect(url: string) {
    if (this.socket) this.disconnect();
    const socketIoConfig: SocketIoConfig = { url };
    this.socket = new Socket(socketIoConfig);
    this.socket.connect();

    this.socket.on("message", (msg) => ... );
    this.socket.on("error", (msg) => ...);
  }
```

**Comment by JeisonJ** [comment]
> I went this route:
> 
> I have two services, each accessing a socket, or in my case, different Namespaces of the same socket.
> In each service, I use the following:
> 
> ```
> @Injectable({providedIn: 'root'})
> export class Socket1 extends Socket {
>   constructor() {
>     super({url: 'https://somefunkydomain:3001/thenamespace', options: {}});
>   }
> }
> ```
> 
> "thenamespace" is all that is changed between the two services.
> In the service constructor:
> public socket: Socket1,
> 
> Now I just access each socket, from each service as I need them.

I have a question, what would app.module.ts look like?

**Comment by hamzahalvanaa** [comment]
is there any workaround? still got problem after tried these two answers above :/

**Comment by deciojr** [comment]
I fixed it by importing the`SocketIoModule` like this `SocketIoModule.forRoot({
 url: ''
})`

**Comment by ctfrancia** [comment]
This issue is over a year old now, if the issue hasn't been resolved then please feel free to open up a new ticket, just so we can track new issues and get rid of the clutter
