### ISSUE TITLE
Is support SSR in angular 7 ? 

### ISSUE THREAD

**Issue by kim257** [rodgc/ngx-socket-io#29]
![image](https://user-images.githubusercontent.com/16816483/53716801-aec2ff00-3e88-11e9-81a7-785132be5d25.png)

My environment
- win 10 enterprise 
- node v8.11.3
- npm 5.6.0

Build SSR file found warning message like this ,but not SSR work normaly .

thank you

**Comment by frabanca** [comment]
Same problem here! 👍

**Comment by caglarturkurka** [comment]
I have same problem. Please tell me how can I solve ngx-socket-io problem using angular universal ?

**Comment by caglarturkurka** [comment]
I solved problem using isPlatformBrowser(this.platformId);
You should use it before socket.emit 
Ex / 
```
if(isPlatformBrowser(this.platformId)) {
 this.socket.emit('online', {
                                ........
                            });
}
```

**Comment by ctfrancia** [comment]
This issue is over a year old now, if the issue hasn't been resolved then please feel free to open up a new ticket, just so we can track new issues and get rid of the clutter

**Comment by Clazherx** [comment]
i have solved this issue with this workaround
>https://github.com/rodgc/ngx-socket-io/issues/105#issuecomment-897863977
