### ISSUE TITLE
Problems using jest and ngx-socket-io

### ISSUE THREAD

**Issue by GregOnNet** [rodgc/ngx-socket-io#32]
## Solution

The solution for this issue is provided in PR #31.

## Problem

Hi @rodgc,

as mentioned in #31 I experience an error if I run jest next to ngx-socket-io.
The current bundle needs to be transformed with babel to get it to work

### Reproduction

I created a repository demoing the problem: https://github.com/GregOnNet/ngx-socket-io-jest-issue

**Steps**

1. git clone https://github.com/GregOnNet/ngx-socket-io-jest-issue.git
2. cd ngx-socket-io-jest-issue
3. npm install
4. npm test

### Workaround

Currently, you need to do the following to get jest to work with ngx-socket-io

1. Install `babel-preset-env`
2. Add `babel.config.js`
3. Configure `jest.setup.js`

**1**

```bash
npm install -D babel-preset-env
```

**2**

```js
// babel.config.js

module.exports = function(api) {
  api.cache(true);

  const presets = ['env'];
  const plugins = [];

  return {
    presets,
    plugins
  };
};
```

**3**

- Tell babel to transform js files
- Add ngx-socket-io to `transformIgnorePatterns` (making jest passing the js files to babel)

```js
module.exports = {
  preset: "jest-preset-angular",
  roots: ["src"],
  setupFilesAfterEnv: ["<rootDir>/src/setup-jest.ts"],
  moduleNameMapper: {
    "@app/(.*)": "<rootDir>/src/app/$1",
    "@assets/(.*)": "<rootDir>/src/assets/$1",
    "@core/(.*)": "<rootDir>/src/app/core/$1",
    "@env": "<rootDir>/src/environments/environment",
    "@src/(.*)": "<rootDir>/src/src/$1",
    "@state/(.*)": "<rootDir>/src/app/state/$1"
  },
  transform: {
    "^.+\\.(ts|html)$":
      "<rootDir>/node_modules/jest-preset-angular/preprocessor.js",
    "^.+\\.js$": "babel-jest"
  },
  transformIgnorePatterns: ["node_modules/(?!(jest-test|ngx-socket-io))"]
};
```

Please let me know if you need further information.

**Comment by z3phyro** [comment]
Hi @GregOnNet, I tried this in my project. Its simply ignoring the babel.conf.js file. I know becuase I introduced a syntax error on it and it wont throw an exception during testing. Rather just show the same error like nothing has been done.

this is my current conf
```
module.exports = {
  "preset": "jest-preset-angular",
  "roots": ["src"],
  moduleNameMapper: {
    "@app/(.*)": "<rootDir>/src/app/$1",
    "@assets/(.*)": "<rootDir>/src/assets/$1",
    "@core/(.*)": "<rootDir>/src/app/core/$1",
    "@env": "<rootDir>/src/environments/environment",
    "@src/(.*)": "<rootDir>/src/src/$1",
    "@state/(.*)": "<rootDir>/src/app/state/$1"
  },
  "setupFilesAfterEnv": ["<rootDir>/setup-jest.ts"],
  "transform": {
    "^.+\\.js$": "babel-jest",
    "^.+\\.(ts|html)$":
      "<rootDir>/node_modules/jest-preset-angular/preprocessor.js"
  },
  "transformIgnorePatterns": [
    "node_modules/(?!(jest-test|ngx-socket-io))"
  ],
  "reporters": [
    "default",
    ["./node_modules/jest-html-reporter", {
      "pageTitle": `Bild Test Report - ${new Date()}`,
      "outputPath": `./test_reports/${new Date().toDateString()}.html`,
      "includeConsoleLog": true
    }]
  ]
};
```

**Comment by z3phyro** [comment]
Silly mistake... I was writing babel.conf.js instead of babel.config.js. Well thanks anyway.

**Comment by ctfrancia** [comment]
This issue is over a year old now, if the issue hasn't been resolved then please feel free to open up a new ticket, just so we can track new issues and get rid of the clutter
