### ISSUE TITLE
url is not honored

### ISSUE THREAD

**Issue by lamba92** [rodgc/ngx-socket-io#33]
Creating a simple socket does not honor the url:
```typescript
export class LogSocket extends Socket {
  constructor(url: string){
    super({url: url, options: {})
  }
}
...
const socket = new LogSocket("http://localhost/api/logs")
```
In the logs I can see that the call is made to `http://localhost/socket.io/?EIO=3&transport=poll` 😕

**Comment by ChrisDoernen** [comment]
Maybe try to put the path (/api/logs) into the path property of the options object. See https://github.com/socketio/socket.io-client/blob/master/docs/API.md#new-managerurl-options

**Comment by ctfrancia** [comment]
This issue is a bit old now, if the issue hasn't been resolved then please feel free to open up a new ticket, just so we can track new issues and get rid of the clutter
