### ISSUE TITLE
Angular 8 - Ivy Support /w ng-packagr

### ISSUE THREAD

**Issue by raphael22** [rodgc/ngx-socket-io#36]
**Issue**: not able to compile angular 8-rc.3 projet with ngx-socket-io

```bash
ERROR in Value at position 1 in the NgModule.importss of SocketModule is not a reference: [object Object]
```

**resolution?** : package lib with ng-packagr in order to generate AOT metadata.

**Comment by Dj-jom2x** [comment]
its perfectly working on mine.. angular 8.1.0-rc.0.. yours i believe is 8.0 rc.3

**Comment by raphael22** [comment]
ou right, fixed with path  of Angular.
