### ISSUE TITLE
Is this repository still maintained?

### ISSUE THREAD

**Issue by wottpal** [rodgc/ngx-socket-io#39]
@rodgc Would be important for us to know if it makes sense to utilize this repo in the future? I think merging some of the PRs would be a great first step to make this project alive again :)

Regards from Germany

**Comment by wottpal** [comment]
@rodgc Fixing the NPM-Warnings would be also a great start :)

```
npm WARN ngx-socket-io@2.1.1 requires a peer of @angular/common@^6.0.0 || ^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-socket-io@2.1.1 requires a peer of @angular/core@^6.0.0 || ^7.0.0 but none is installed. You must install peer dependencies yourself.
```

**Comment by jllodra** [comment]
I'm in the same situation. If you know of any up-to-date fork, please let me know.

**Comment by edgarinoaz** [comment]
Just run: `npm audit fix` . All warnings are thrown by lodash

**Comment by spock123** [comment]
This library also throws error when trying out IVY (9.0.0-next.2)

**Comment by ctfrancia** [comment]
see #49
