### ISSUE TITLE
Angular 6: Property 'ɵNgModuleInjector' does not exist

### ISSUE THREAD

**Issue by codetinker** [rodgc/ngx-socket-io#4]
Hello,

I just upgraded to angular 6. All working except ngx-socket-io.
When starting apps it give error:
`Property 'map' does not exist on type 'Observable<{}>'`

I'm sure map and Observable is properly imported. So i tried to import ngx-socket-io manually to my project. Then it show this error:

`ERROR in src/app/shares/ngx-socket-io/socket-io.module.ngfactory.ts(11,46): error TS2339: Property 'ɵNgModuleInjector' does not exist on type 'typeof "W:/Webs/myapp/node_modules/@angular/core/core"'.src/app/shares/ngx-socket-io/socket-io.module.ngfactory.ts(27,88): error TS2511: Cannot create an instance of an abstract class.`

**Comment by qq289089000** [comment]
me too

**Comment by paullryan** [comment]
Either update to 1.1.0 or use rxjs-compat
