### ISSUE TITLE
Event not work after manual reconnect

### ISSUE THREAD

**Issue by decad7never** [rodgc/ngx-socket-io#40]
Hello,

I have a big issue with my app, i try to find a solution to reconnect my socketio connection manualy. I explain my issue.

I developped an app with a little chat, the frontend with angular7, and the backend with nodejs. When i connect to my app with my login, all works correctly, i received my data from the backend, all of my events works also, its great !

But when i refresh the page, i catch the io server disconnect event on disconnect, and i try to reconnect the socket manualy.

```
case 'io server disconnect':
                 
   this.socket.ioSocket.io.opts.query = {
                        origin: '*',
                        reconnect: true,
                        reconnectionDelay: 1000,
                        reconnectionDelayMax: 5000,
                        reconnectionAttempts: Infinity,
                        autoConnect: true,
                        forceNew: true,
                        reconnection: true,
                        secure: environment.chat.socket.secure
                    }; // new options

                    // Add url of the socket
                    this.socket.ioSocket.io.uri = environment.chat.socket.url + ':' + environment.chat.socket.port;

                    // Connect the socket
                    this.socket.connect(); // manually connection
                    break;
```

But i received nothing from event, all events are completly disconnected to the socket. 
However when i check with console.log the content of my socket, the socket is connected.....

it's been two days since I can not find a solution

Can you help me please ?

Thanks

Regards

Decad7

**Comment by awallat** [comment]
I have the same problem, after a manual reconnect I cannot get any events from the socket!

**Comment by ctfrancia** [comment]
if this issue hasn't been resolved please open up a new ticket, I am trying to clear up some of the clutter so we have a sense of new issues.
