### ISSUE TITLE
socket.id undefinded and connect event first time not working

### ISSUE THREAD

**Issue by JeongSeho** [rodgc/ngx-socket-io#42]
const connection = this.socket.connect();
console.log(connection)

this.socket.fromEvent('connect').subscribe(()=>{
 console.log('connect')
})

![image](https://user-images.githubusercontent.com/24802694/63220007-d1886c00-c1b9-11e9-8f3c-bbfde1f605f9.png)

why connect event callback firsttime?
and socket.id undefinded?

**Comment by andypopa** [comment]
Hi,

You might see the id in the console but be unable to access it.

To fix this, make sure you're trying to get the id after the connection has been established.

`  
socketId = null;

constructor(
    private socket: Socket
  ) { 
    this.socket.on('connect', (_socket) => {
      this.socketId = this.socket.ioSocket.id;
    });
  }
`

**Comment by ctfrancia** [comment]
If this issue hasn't been resolved then please open up a new ticket. For now I am closing this issue as the last response was 3 months ago.
