### ISSUE TITLE
socket.emit() typings are too restrictive

### ISSUE THREAD

**Issue by miso440** [rodgc/ngx-socket-io#45]
According to [Socket IO's official documentation](https://socket.io/docs/client-api/#socket-emit-eventName-%E2%80%A6args-ack), client-side `socket.emit()` accepts any number of arguments, where the first is a `string` and the last _may_ be a `Function`. Currently, the type definitions for the `socket.emit()` method accepts only a single argument of `any` type between the event name and callback function.

For our application, we need to be able to pass multiple data arguments with `socket.emit`, and so are using a fork of this with the necessary changes. We'd like to see those changes in this repository, though.

**Comment by ctfrancia** [comment]
I put in a note to the owner to merge the pull request, I know it's been a while, but, better than never I suppose sorry.

**Comment by rodgc** [comment]
PR has been  merged
