### ISSUE TITLE
socket disconnect after make mobile browser onpause

### ISSUE THREAD

**Issue by marwenktata** [rodgc/ngx-socket-io#47]
socket disconnect after make mobile browser onpause in android and iphone
 ---->my setting  :
   allowUpgrades: false,
upgradeTimeout:60000,
reconnection: false,
pingInterval: 40000,
pingTimeout:60000,
reconnectionDelay: 5000,

**Comment by ctfrancia** [comment]
Is this issue persisting? or can we close the issue?

**Comment by sucotronic** [comment]
No info provided to replicate.
