### ISSUE TITLE
Support for Angular 6

### ISSUE THREAD

**Issue by becerriljc** [rodgc/ngx-socket-io#5]
I'm trying Angular 6 with this package and to run the app appear this error: 
ERROR in ./node_modules/ngx-socket-io/src/socket-io.service.js
Module not found: Error: Can't resolve 'rxjs/Observable'

Any solution?

**Comment by CrackerakiUA** [comment]
had same problem, my steps to solution was:
```npm i --save rxjs
npm i --save rxjs-compat
```
and there will be global but which you can solve by putting below code
```(window as any).global = window;```
anywhere in polyfills.ts file

**Comment by becerriljc** [comment]
i try your solution and i can solve it! Thanks!
