### ISSUE TITLE
 ERROR in node_modules/ngx-socket-io/src/socket-io.module.d.ts:8:45 - error NG6005

### ISSUE THREAD

**Issue by Thomasfds** [rodgc/ngx-socket-io#56]
Hello, 

I have this error on my console after initial config in app.module on Angular 9.

ERROR in node_modules/ngx-socket-io/src/socket-io.module.d.ts:8:45 - error NG6005: SocketIoModule.forRoot returns a ModuleWithProviders type without a generic type argument. Please add a generic type argument to the ModuleWithProviders type. If this occurrence is in library code you don't control, please contact the library authors.

Any idea ?

**Comment by rodgc** [comment]
Hello,

This ERROR has been fixed on v3.2.0
