### ISSUE TITLE
Can not receive and send events

### ISSUE THREAD

**Issue by RonRofe** [rodgc/ngx-socket-io#57]
I have implemented `socket-io` server in my app and I am using `ngx-socket-io` for my `Angular` application communicating with that server.

My server implementation:
```javascript
const io = socketio(server);

io.on('connection', socket => {
    console.log('connection!')
    socket.emit('notification');
});
```

After connecting to my app, the `connection!` message is printed successfully, means the client successfully linked to the WS server.

But my `notification` event listener is not receiving any events...

My `WebSocketService`:
```typescript
import { Injectable } from '@angular/core';
import { Socket } from 'ngx-socket-io';

@Injectable()
export class WebSocketService {
    constructor(
        private socket: Socket,
    ) {}

    public getEventListener() {
        return this.socket.fromEvent('notification');
    }
}
```

Subscription (In other service):

```typescript
@Injectable()
export class NotificationService {
    ...

    constructor(
        private wsService: WebSocketService,
    ) {
        console.log('Test')
        this.wsService.getEventListener().subscribe(() => console.log(123));
    }

    ...
}
```

`Test` is printed but 123 is not.

**Comment by 3adeling** [comment]
hey @RonRofe. please what was the solution for this issue?

**Comment by RonRofe** [comment]
> hey @RonRofe. please what was the solution for this issue?

Hi,

Solution is here:
https://stackoverflow.com/questions/61571898/rxjs-websocket-websocket-connection-to-ws-localhost3000-failed-connecti

It worked, but it was less convenient than expected so I decided to use ngx-socket-io. Really recommend you to do the same.
