### ISSUE TITLE
Angular 10 support

### ISSUE THREAD

**Issue by cloakedch** [rodgc/ngx-socket-io#61]
An Angular 9 app can't be updated to the latest Angular 10 release, since this library does not support it:

```
Package "ngx-socket-io" has an incompatible peer dependency to "@angular/core" (requires "^8.0.0" (extended), would install "10.0.0").
Package "ngx-socket-io" has an incompatible peer dependency to "@angular/common" (requires "^8.0.0" (extended), would install "10.0.0").
```

Could you update your package.json file?

**Comment by rodgc** [comment]
`Angular` 10 support added on Release 3.2.0

**Comment by CrackerakiUA** [comment]
remove of incompatible peer is only fix, on my side socket.on is no longer working on angular 10, is this something only on my side?
