### ISSUE TITLE
ngx-socket-io 3.2.0 requires Angular 10+ as peer dependency

### ISSUE THREAD

**Issue by ldariom** [rodgc/ngx-socket-io#73]
I have a dependency problem with the latest version of ngx-socket-io I am subject to other dependencies that my environment does not work in angular 10, so if I downgrade to 3.0.1 angular 8 is not possible, I do install version 3.2 .0, it asks me for angular 10.
What should I do to make the dependencies stable in angular 9?
![image](https://user-images.githubusercontent.com/14187352/93023496-aefc9880-f5ef-11ea-9c9b-6a2ba730db76.png)

Regards Dario

**Comment by Helveg** [comment]
Could you try version 3.1.0?

**Comment by idsplus-carlos** [comment]
Same here, maybe it's a problem with npm's registry?
```bash
$ npm show ngx-socket-io@* version
ngx-socket-io@1.0.0 '1.0.0'
ngx-socket-io@1.0.1 '1.0.1'
ngx-socket-io@0.0.0 '0.0.0'
ngx-socket-io@1.0.4 '1.0.4'
ngx-socket-io@1.0.5 '1.0.5'
ngx-socket-io@1.0.3 '1.0.3'
ngx-socket-io@1.0.6 '1.0.6'
ngx-socket-io@1.0.7 '1.0.7'
ngx-socket-io@1.0.8 '1.0.8'
ngx-socket-io@1.1.0 '1.1.0'
ngx-socket-io@1.1.1 '1.1.1'
ngx-socket-io@2.0.0 '2.0.0'
ngx-socket-io@2.1.0 '2.1.0'
ngx-socket-io@2.1.1 '2.1.1'
ngx-socket-io@3.0.1 '3.0.1'
ngx-socket-io@3.2.0 '3.2.0'
```

No 3.1.0 there.

**Comment by Helveg** [comment]
There's a 3.1.0 release here on GitHub, I thought that it was for Angular 9, but it was shortlived and succeeded by Angular 10 on 3.2.0

**Comment by ldariom** [comment]
Hello, I tried to install version 3.1.0 but this version does not exist, is it possible that a version that solves this problem will see the light?
Thank you

**Comment by Helveg** [comment]
As mentioned above it's a GitHub only release, try adding it to your package.json this way:

```json
{
  "ngx-socket-io": "rodgc/ngx-socket-io#v3.1.0"
}
```

**Comment by ldariom** [comment]
Fixed the npm has run out of errors.
thank you

**Comment by Helveg** [comment]
I'm closing this issue. Feel free to ask more questions :)

**Comment by ldariom** [comment]
Hello again,
Compile timing was not good
![image](https://user-images.githubusercontent.com/14187352/93251695-cd4fc900-f794-11ea-926f-244188eca1c7.png)
Version 3.2.0 if it compiles, I will switch to it to continue development.
There may be some solution?

**Comment by Helveg** [comment]
I guess we could accept Angular 7-10 as peer dependencies rather than strictly requiring Angular 10?
