### ISSUE TITLE
Cannot get connection state

### ISSUE THREAD

**Issue by rinelfi-git** [rodgc/ngx-socket-io#74]
How could I get the connection state of the client to server?
I tried `socket.connected` but it is not supported

**Comment by arturfigueira** [comment]
You can access socket.io's socket through ngx socket. With that you can call socket.connected as you mentioned.

Angular2 example:
`
import { Injectable } from '@angular/core';
import { Socket } from 'ngx-socket-io';
import { Socket as ioSocket } from 'socket.io-client';
@Injectable({
  providedIn: 'root',
})
export class MyService {
  constructor(private socket: Socket) {
    const ioSocket = this.socket.ioSocket as ioSocket;
    if (!ioSocket.connected) {
      console.log('Not connected');
    }
  }
}
`

**Comment by arturfigueira** [comment]
You can access socket.io-client's socket through ngx socket instance. With that you can call socket.connected as you mentioned.

Angular2 example:
```
import { Injectable } from '@angular/core';
import { Socket } from 'ngx-socket-io';
import { Socket as ioSocket } from 'socket.io-client';
@Injectable({
  providedIn: 'root',
})
export class MyService {
  constructor(private socket: Socket) {
    const ioSocket = this.socket.ioSocket as ioSocket;
    if (!ioSocket.connected) {
      console.log('Not connected');
    }
  }
}
