### ISSUE TITLE
NullInjectorError: No provider for WrappedSocket!

### ISSUE THREAD

**Issue by Nillcon248** [rodgc/ngx-socket-io#76]
When I try to import SocketIoModule without .forRoot(config), i get this error. I want to make some action with params in my socket service, but config is adding in module.

![image](https://user-images.githubusercontent.com/40437610/97763325-ea0d4980-1b13-11eb-8da4-b5be4da759e9.png)
![image](https://user-images.githubusercontent.com/40437610/97763358-0ad59f00-1b14-11eb-963b-e204727d72a2.png)

![image](https://user-images.githubusercontent.com/40437610/97763387-1d4fd880-1b14-11eb-873d-dce6cbe9f400.png)

**Comment by jeffersonveloso** [comment]
I have this same problem, some solution?

**Comment by sucotronic** [comment]
Duplicated #55
