### ISSUE TITLE
Upgrade to Socket.IO v3

### ISSUE THREAD

**Issue by flolu** [rodgc/ngx-socket-io#78]
Currently the dependency of `socket.io-client` is at version `2.2.0`.
Would be awesome if someone could upgrade to `v3`

**Comment by Noaber** [comment]
Could anyone please answer this ? Thanks in advance

**Comment by flolu** [comment]
@Noaber I would advise you implement it yourself. (with the [socket.io-client](https://github.com/socketio/socket.io-client#readme) package) It is not that complicated.
You can look at a working example [here](https://github.com/flolu/angular-bazel-starter/blob/33091fc5c2d59933e27462f56c462ed74b0df9be/services/client/features/realtime/quote.effects.ts#L6).

**Comment by Noaber** [comment]
Thanks for your answer, however don't we get out of sync with this package ?

**Comment by flolu** [comment]
Yeah, you're right. But honestly, the whole package is just [90 lines of code](https://github.com/rodgc/ngx-socket-io/blob/master/src/socket-io.service.ts). You can just add that file into your own project with the latest version of socket.io-client.

**Comment by LeonardoRick** [comment]
would be awesome if this project update to `v3`
