### ISSUE TITLE
Connect to url set by user interaction

### ISSUE THREAD

**Issue by Dealerpriest** [rodgc/ngx-socket-io#79]
Isn't there a way to connect to a url chosen by the user? How could one achieve that?

My sceanrio. I have an app where the backend could run on different domains. I want the user to be able to use an input field to set which url the socket should connect to. Is this possible?

**Comment by Helveg** [comment]
Yes this is possible. Sockets can be generated dynamically:

```typescript
import { Socket, SocketIoConfig } from 'ngx-socket-io';

let cfg: SocketIoConfig = {url: "https://localhost/ws"};
let socket = new Socket(cfg);
```

**Comment by Doc999tor** [comment]
I have a related problem: I need to connect to socket but after some time
I can create `new Socket` instance, but how can I connect it to angular DI? Like it traditionally initialized by `app.module`'s `imports: [ SocketIoModule.forRoot(config) ]`

**Comment by Helveg** [comment]
That's not the recommended way to do it; You'd be better of creating a service that manages your sockets then. That way you can DI the service everywhere and access the correct socket through the service.
