### ISSUE TITLE
Angular 6 - share function

### ISSUE THREAD

**Issue by becerriljc** [rodgc/ngx-socket-io#8]
Im using "ngx-socket-io": "^1.1.0" and "rxjs-compat": "^6.2.1" at run my app have this issue:

ERROR TypeError: rxjs__WEBPACK_IMPORTED_MODULE_1__.Observable.create(...).share is not a function at WrappedSocket.push../node_modules/ngx-socket-io/src/socket-io.service.js.WrappedSocket.fromEvent

Thanks.

**Comment by mmenik** [comment]
same problem

**Comment by mahran419** [comment]
same problem

**Comment by rodgc** [comment]
Solved in version 1.1.1
