### ISSUE TITLE
CommonJS or AMD dependencies can cause optimization bailouts

### ISSUE THREAD

**Issue by dj-fiorex** [rodgc/ngx-socket-io#80]
Hello, i'm trying to use your library in my Angular 10 project, but when i build i receive this warning:
`WARNING in C:\Users\carme\Documents\Haptica\LineaVita\Web\linea-vita\node_modules\ngx-socket-io\__ivy_ngcc__\fesm2015\ngx-socket-io.js depends on 'socket.io-client'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies`

How can i fix this warning?

**Comment by Helveg** [comment]
Follow the link in your error: https://angular.io/guide/build#configuring-commonjs-dependencies

And execute the steps there. I don't think there's anything we can do since we're a wrapper around that dependency.
