### ISSUE TITLE
Can't connect to server because of CORS (Reason: CORS header ‘Access-Control-Allow-Origin’ missing)

### ISSUE THREAD

**Issue by k-matti** [rodgc/ngx-socket-io#82]
This is my app.module.ts:

```
import { SocketIoModule, SocketIoConfig } from 'ngx-socket-io';

const config: SocketIoConfig = { url: 'http://localhost:4000', options: {} };

@NgModule({
  declarations: [AppComponent, MapComponent],
  imports: [BrowserModule, HttpClientModule, SocketIoModule.forRoot(config)],
  providers: [],
  bootstrap: [AppComponent],
})
export class AppModule {}
```

this is my server:
```

const server = require('http').createServer();
const options = {
  origin: '*',
  methods: ['GET', 'POST'],
};

server.listen(4000, () => {
  console.log('Server ready....');
});

const io = require('socket.io')(server, options);

io.on('connection', (socket) => {
  console.log('Connected');
  socket.emit('data', JSON.stringify(data));

});
```
This is how I am trying to get data from socket server in my service:
```

  getMarkers(): Observable<IMarker[]> {
    return this.socket.fromEvent<string>('data').pipe(map((data: string) => JSON.parse(data)));
  }
```

Every time I open localhost:4200 I get CORS error:

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:4000/socket.io/?EIO=3&transport=polling&t=NReqqZ8. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).`

Don't know what to set here to make CORS works:

```
const options = {
  origin: '*',
  methods: ['GET', 'POST'],
};
```

**Comment by Helveg** [comment]
You'll have to add CORS headers to your HTTP server. There's a ton of guides on how to achieve this. I'll be closing this issue. If you find any specific difficulties of adding CORS because of `ngx-socket-io` please feel free to comment!

**Comment by k-matti** [comment]
How to completly disable cors? I am using ng serve to run my app. I think the problem is something in ngx-socket-io because when i use react client app with the same socket server everything works fine

**Comment by Helveg** [comment]
CORS is enforced by the browser, you could maybe set a sort of developer flag but your server will have to deal with CORS or your users who don't have that flag set won't be able to visit your app.

**Comment by k-matti** [comment]
I fixed CORS issue by adding this to config in my app:

```
SocketIoModule.forRoot({
      url: 'http://localhost:4000',
      options: {
        withCredentials: false,
      },
    }),
```

server: 

```
const server = require('http').createServer();
const options = {
  cors: {
    origin: '*',
  },
};

const io = require('socket.io')(server, options);

io.on('connection', (socket) => {
  console.log('Connected');
});

server.listen(4000);
```

But still on app start i am not connected to socket, can't see connected in the console

**Comment by Helveg** [comment]
Any errors? You'd have to show us the code you use to connect to the server, but a better place for troubleshooting is on other community channels like StackOverflow.
