### ISSUE TITLE
New Connection every 5 sek

### ISSUE THREAD

**Issue by DanielDanninger** [rodgc/ngx-socket-io#87]
It looks like version 3.3 is opening a new socket connection every 5 sek. 
I got an working projekt with version 3.2 that behaves normal, after upgrading i see a new connect from a single client every 5 sek.
After downgrading the issue is gone again.

**Comment by ivikiwi** [comment]
i have the same issue. Emitting and receiving data is also not possible with version 3.3

**Comment by Leon-Bor** [comment]
Same issue here with 3.3.0. Downgraded to v `3.2.0 `to work again

**Comment by maxfloden** [comment]
> i have the same issue. Emitting and receiving data is also not possible with version 3.3

I spent hours on this - emit not working - downgrading to 3.2 fixed it - thanks @ivikiwi

**Comment by sucotronic** [comment]
What socket-io version do you have installed on the server side? the 3.3 ngx-socket-io version es meant to be paired with the 4.0.0 version of the socket-io server side version.

**Comment by DanielDanninger** [comment]
I am using nest.js, that got an inbuild wrapper arround the socket.io stuff. I guess its not using socket.io 4.0. Maybe make it more clear that this version NEEDS socket.io 4.0.
