### ISSUE TITLE
The on event for `connect` does not work 

### ISSUE THREAD

**Issue by bnupy** [rodgc/ngx-socket-io#90]
`ngx-socket-io` coming from `ng-socket-io` library.
 The socket `on` event for `connect` doesn't seem to work.
The functionality used to work in the previous package.
 
 
 ```
 this.socket.on('connect', () => {
        console.log('connect')
});
```

**Comment by Helveg** [comment]
Do your Socket.IO versions match client and server side?

**Comment by hugoebarboza** [comment]
Hello @Helveg and @bnupy , I have the same issue The on event for connect does not work, so which server side version works with ngx-socket-io@3.3.0 ?

**Comment by Helveg** [comment]
Socket.IO v4.0

**Comment by Ruslancic** [comment]
Same here +1

**Comment by darksider458** [comment]
we had a similar issue 

our package.json had "ngx-socket-io": "^3.2.0", which made so in our production it installed 3.3.0 which caused issues as our server was using older version. the best fix for it was to change "ngx-socket-io": "^3.2.0", to "ngx-socket-io": "~3.2.0",

thou i would recommend to the people working on this package to rename 3.3.0 to 4.0.0 to prevent issues similar to this

**Comment by Helveg** [comment]
| thou i would recommend to the people working on this package to rename 3.3.0 to 4.0.0 to prevent issues similar to this

Estimating from the high number of traffic on this issue that seems like a good idea, @rodgc ?

**Comment by rodgc** [comment]
Release two new versions to fix this problem.

Release v3.3.1 for developers who are not using socket-io v4 on their server and v4.0.0 for the developer using it.
