### ISSUE TITLE
not able to connect to ioserver(node server)

### ISSUE THREAD

**Issue by gsudhanshu** [rodgc/ngx-socket-io#91]
my config:

```
const config: SocketIoConfig = { url: 'ws://localhost:8001', options: { transports : ['websocket'] } };
```

when I try to use http then I get cors error

I am using socket.io 3.1.0 and these config work from plain javascript

**Comment by Helveg** [comment]
Could you provide more detailed information such as:

* A minimally reproducible example
* The complete error

**Comment by gsudhanshu** [comment]
@Helveg thanks for your reply.

The problem resolved. problem was incompatible version numbers

**Comment by Helveg** [comment]
Glad you fixed it! :)
