### ISSUE TITLE
Soket4.0.0 is not working propely

### ISSUE THREAD

**Issue by shubhamm78** [rodgc/ngx-socket-io#95]
this version of socket not emiting the events but on the previous version is working well, and also not genrating ioSocket id

**Comment by Helveg** [comment]
Can you provide additional information please, such as a minimally reproducible example, and the version of SocketIO that the server is using?

**Comment by shubhamm78** [comment]
On the server side i'm using socket.io version2.3.0
And on the client site i was using latest version on ngx socket that is 4.0.0,

**Comment by Helveg** [comment]
Ah ok, well `ngx-socket-io` 4 uses Socket.IO 4, you can have a look at the version requirements [here](https://github.com/rodgc/ngx-socket-io#install) 😄
