### ISSUE TITLE
Error: getInternalNameOfClass() called on a non-ES5

### ISSUE THREAD

**Issue by alexisperezglez** [rodgc/ngx-socket-io#96]
I got this error on ng build --prod with angular v9.1.11

![image](https://user-images.githubusercontent.com/37912015/116600017-cfffc880-a8f6-11eb-8470-fdc6ac015648.png)

**Comment by Helveg** [comment]
Big error message so maybe I missed it, but how does this relate to this package? It's also possible that for Angular 9 you'll require a lower `ngx-socket-io` package

**Comment by jrmykolyn** [comment]
Hey @alexisperezglez,

For what it's worth, the error originates from the following code within Angular's compiler CLI: https://github.com/angular/angular/blob/9.0.x/packages/compiler-cli/ngcc/src/host/esm5_host.ts#L85. You may get some additional insight by poking around there.

You may also want to share:

- Your package JSON file (or at least the version of `ngx-socket-io` that you're using).
- A code snippet that illustrates how you're importing and configuring the `SocketIoModule`.
- Any notes on whether you're encountering this during local development or _only_ when you're building the application bundles?
